# Project Metadata
sonar.projectKey=mrrobot7781_project-xdr
sonar.organization=mrrobot7781
sonar.sources=.

# General Exclusions (Coverage check hata diya)
sonar.exclusions=**/tests/**,**/scripts/**,**/.github/**

# Fail pipeline if Quality Gate fails
sonar.qualitygate.wait=true
