# Project Metadata
sonar.projectKey=mrrobot7781_project-xdr
sonar.organization=mrrobot7781
sonar.sources=.

# Coverage and General Exclusions
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**,**/scripts/**,**/test_*.py,app.py
sonar.exclusions=**/tests/**,**/scripts/**,**/.github/**

# Fail pipeline if Quality Gate fails
sonar.qualitygate.wait=true
